package com.cursosdedesarrollo.app;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SocialdemocraciaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void socialdemocraciaTest() {
    driver.get("https://es.wikipedia.org/wiki/Wikipedia:Portada");
    driver.manage().window().setSize(new Dimension(1850, 1053));
    driver.findElement(By.id("searchInput")).click();
    driver.findElement(By.id("searchInput")).sendKeys("socialdemocracia");
    driver.findElement(By.cssSelector(".suggestions-result-current > .highlight")).click();
    driver.findElement(By.cssSelector(".tocsection-5 .toctext")).click();
    driver.findElement(By.cssSelector("p:nth-child(42) > a")).click();
    driver.findElement(By.id("firstHeading")).click();
    assertThat(driver.findElement(By.id("firstHeading")).getText(), is("Socialismo democrático"));
  }
}
